apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.1
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - test  
              - "!"  
              - "-f"
              - /tmp/killswitch
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - test  
              - "!"  
              - "-f"
              - /tmp/maintenance
          initialDelaySeconds: 5
          timeoutSeconds: 5
